### ISSUE TITLE
seems to be an error in command string

### ISSUE THREAD

**Issue by kuilef** [saiprashanths/dl-docker#1]
command like

`docker run -it -p 8888:8888 6006:6006 -v /sharedfolder:/root/sharedfolder dl-docker:cpu bash`
doesn't work on my PC

`docker run -it -p 8888:8888 -p 6006:6006 -v /sharedfolder:/root/sharedfolder dl-docker:cpu bash`
works.

Please check this on README.md

**Comment by saiprashanths** [comment]
Good catch, thanks! I've updated the Readme.md
