### ISSUE TITLE
W: Failed to fetch http://ppa.launchpad.net/jtaylor/ipython/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

### ISSUE THREAD

**Issue by PhDCK** [saiprashanths/dl-docker#10]
错误1：
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe python-software-properties all 0.92.37.7 [19.6 kB]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
解决方案：
明明设了环境变量DEBIAN_FRONTEND=noninteractive却失效了，解决方法如下：
#F1： sudo apt-get install dialog 或 sudo apt-get install whiptail（试了没用）
#F2： sudo dpkg-reconfigure debconf 手动选noninteractive，级别选high
错误2：
==> Found Ubuntu version 14.xx
gpg: keyring `/tmp/tmpjn9rgx44/secring.gpg' created
gpg: keyring `/tmp/tmpjn9rgx44/pubring.gpg' created
gpg: requesting key 58B80F90 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpjn9rgx44/trustdb.gpg: trustdb created
gpg: key 58B80F90: public key "Launchpad PPA for Julian Taylor" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
错误3：

W: Failed to fetch http://ppa.launchpad.net/jtaylor/ipython/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by saiprashanths** [comment]
This could be a temporary server issue with launchpad. I'd recommend waiting for a few hours and trying again. If you continue to face issues, you can post your questions on the [launchpad forum](https://answers.launchpad.net/ubuntu)
