### ISSUE TITLE
Jupyter Kernel Restarting

### ISSUE THREAD

**Issue by robinloxley1** [saiprashanths/dl-docker#3]
Using the original docker image CPU version, jupyter keep restarting util Status 410 .

if Running 

docker run with command "jupyter notebook"

However, no problem if docker run bash and juypter notebook inside.

debug info as:

[D 09:07:02.453 NotebookApp] 200 GET /static/base/images/favicon.ico?v=30780f272ab4aac64aa073a84154
6240 (10.10.1.14) 1.04ms
[D 09:07:02.661 NotebookApp] Initializing websocket connection /api/kernels/aa078a82-80ce-404e-a042
-d55af19ff806/channels
[D 09:07:02.666 NotebookApp] Requesting kernel info from aa078a82-80ce-404e-a042-d55af19ff806
[D 09:07:02.666 NotebookApp] Connecting to: tcp://127.0.0.1:55924
[I 09:07:05.146 NotebookApp] KernelRestarter: restarting kernel (1/5)
[D 09:07:05.147 NotebookApp] Starting kernel: [u'/usr/bin/python', u'-m', u'ipykernel', u'-f', u'/r
oot/.local/share/jupyter/runtime/kernel-aa078a82-80ce-404e-a042-d55af19ff806.json']
[D 09:07:05.151 NotebookApp] Connecting to: tcp://127.0.0.1:51770
[I 09:07:08.154 NotebookApp] KernelRestarter: restarting kernel (2/5)
[D 09:07:08.155 NotebookApp] Starting kernel: [u'/usr/bin/python', u'-m', u'ipykernel', u'-f', u'/r
oot/.local/share/jupyter/runtime/kernel-aa078a82-80ce-404e-a042-d55af19ff806.json']
[D 09:07:08.158 NotebookApp] Connecting to: tcp://127.0.0.1:51770
[I 09:07:11.161 NotebookApp] KernelRestarter: restarting kernel (3/5)
[D 09:07:11.161 NotebookApp] Starting kernel: [u'/usr/bin/python', u'-m', u'ipykernel', u'-f', u'/r
oot/.local/share/jupyter/runtime/kernel-aa078a82-80ce-404e-a042-d55af19ff806.json']
[D 09:07:11.165 NotebookApp] Connecting to: tcp://127.0.0.1:51770
[W 09:07:12.669 NotebookApp] Timeout waiting for kernel_info reply from aa078a82-80ce-404e-a042-d55
af19ff806
[D 09:07:12.670 NotebookApp] Opening websocket /api/kernels/aa078a82-80ce-404e-a042-d55af19ff806/ch
annels
[D 09:07:12.670 NotebookApp] Connecting to: tcp://127.0.0.1:55924
[D 09:07:12.671 NotebookApp] Connecting to: tcp://127.0.0.1:48445
[D 09:07:12.671 NotebookApp] Connecting to: tcp://127.0.0.1:48030
[I 09:07:14.166 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel aa078a82-80ce-404e-a042-d55af19ff806 restarted
[D 09:07:14.167 NotebookApp] Starting kernel: [u'/usr/bin/python', u'-m', u'ipykernel', u'-f', u'/r
oot/.local/share/jupyter/runtime/kernel-aa078a82-80ce-404e-a042-d55af19ff806.json']
[D 09:07:14.171 NotebookApp] Connecting to: tcp://127.0.0.1:51770
[W 09:07:17.173 NotebookApp] KernelRestarter: restart failed
[W 09:07:17.173 NotebookApp] Kernel aa078a82-80ce-404e-a042-d55af19ff806 died, removing from map.
ERROR:root:kernel aa078a82-80ce-404e-a042-d55af19ff806 restarted failed!
[D 09:07:17.447 NotebookApp] Websocket closed aa078a82-80ce-404e-a042-d55af19ff806:87779D93702E4247
BD06F3D850663D80
[W 09:07:17.453 NotebookApp] Kernel deleted before session
[W 09:07:17.453 NotebookApp] 410 DELETE /api/sessions/afffdc73-07f9-471d-adfe-2b3504a9f8f1

**Comment by saiprashanths** [comment]
Can you please try this? `docker run -it -p 8888:8888 -p dl-docker:cpu bash /root/run_jupyter.sh`

**Comment by saiprashanths** [comment]
Jupyter has issues with being run directly: `https://github.com/ipython/ipython/issues/7062`. Wrapping it up in a shell script and running that, as noted above, should work. Closing this.
