### ISSUE TITLE
Torch Docker link broken

### ISSUE THREAD

**Issue by Kaixhin** [saiprashanths/dl-docker#4]
I've finally moved "cuda-torch-plus" into a separate repo as it doesn't fit the "minimum viable build" principle for my Dockerfiles. It's up to you whether you want to change the link to the [normal image](https://github.com/Kaixhin/dockerfiles/tree/master/cuda-torch/cuda_v7.5) or the [mega image](https://github.com/Kaixhin/docker-torch-mega).

FYI many people will be upgrading to CUDA 8.0 when it comes out later this year, so keep that in mind for this repo~

**Comment by saiprashanths** [comment]
Thanks for the heads up Kai! I've updated the README to link to the Torch normal image. The mega image might be an overkill.

Yes, I'll update to CUDA 8.0 once the frameworks start supporting it.
