### ISSUE TITLE
Downloaded the Docker image from Docker Hub and then "Unable to find image 'dl-docker:cpu' locally"

### ISSUE THREAD

**Issue by paultpearson** [saiprashanths/dl-docker#6]
I am unable to get the docker image downloaded from Docker Hub to run on my Windows 7 machine.  I opened Docker Quickstart Terminal, downloaded the docker image from Docker Hub via

docker pull floydhub/dl-docker:cpu

but when I try to run the docker image using

docker run -it -p 8888:8888 -p 6006:6006 -v /sharedfolder:/root/sharedfolder

I get error messages

Unable to find image 'dl-docker:cpu' locally
Pulling repository docker.io/library/dl-docker
C:\Program Files\Docker Toolbox\docker.exe: Error: image library/dl-docker not found.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

that I do not know how to resolve.  As someone who is new to Docker, I appreciate any help you can provide.  The log of the Docker Quickstart Terminal is below in case it helps with troubleshooting.

Thank you!

##########################################################
#  From Docker Quickstart Terminal

Creating CA: C:\Users\sumloan\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\sumloan\.docker\machine\certs\cert.pem
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\sumloan\.docker\machine\cache\boot2docker.iso to C:\U
sers\sumloan\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to create a network adapter. Some
times, such confirmation window is minimized in the taskbar.
(default) Found a new host-only adapter: "VirtualBox Host-Only Ethernet Adapter
#2"
(default) Windows might ask for the permission to configure a network adapter. S
ometimes, such confirmation window is minimized in the taskbar.
(default) Windows might ask for the permission to configure a dhcp server. Somet
imes, such confirmation window is minimized in the taskbar.
(default) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this vi
rtual machine, run: C:\Program Files\Docker Toolbox\docker-machine.exe env defau
lt

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

Start interactive shell

sumloan@SUMLOAN02 MINGW64 ~
$ docker pull floydhub/dl-docker:cpu
cpu: Pulling from floydhub/dl-docker

6c953ac5d795: Pull complete
3eed5ff20a90: Pull complete
f8419ea7c1b5: Pull complete
51900bc9e720: Pull complete
a3ed95caeb02: Pull complete
ea4d432a81d9: Pull complete
4b76eadf67da: Pull complete
25dc96fefbf0: Pull complete
dc1a046fded2: Pull complete
887580a15226: Pull complete
2c451332fccf: Pull complete
ab2009e7ad9e: Pull complete
48eb8f380019: Pull complete
d17800e4c264: Pull complete
18d662f15986: Pull complete
1ef83d1b7232: Pull complete
c913c41e5e86: Pull complete
e7870eb751ec: Pull complete
93a1800a0c5e: Pull complete
1394f32c5367: Pull complete
9ab3142d7018: Pull complete
Digest: sha256:796ce6a1e862b5a80cac7896da6cbb22c2532432674beec98753453f67b030b8
Status: Downloaded newer image for floydhub/dl-docker:cpu

sumloan@SUMLOAN02 MINGW64 ~
$ docker run -it -p 8888:8888 -p 6006:6006 -v /sharedfolder:/root/sharedfolder
dl-docker:cpu bash
Unable to find image 'dl-docker:cpu' locally
Pulling repository docker.io/library/dl-docker
C:\Program Files\Docker Toolbox\docker.exe: Error: image library/dl-docker not found.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by saiprashanths** [comment]
When you run it, try `docker run -it -p 8888:8888 -p 6006:6006 -v /sharedfolder:/root/sharedfolder
floydhub/dl-docker:cpu bash`. I'll update the documentation accordingly

**Comment by paultpearson** [comment]
Thanks!  Adding "floydhub/" to the docker run command worked.  Since "dl-docker:cpu" and "dl-docker:gpu" appear in several places in the README.md file, you may need to update every time they occur with "floydhub/dl-docker:cpu" and "floydhub/dl-docker:gpu" (but I'm not sure).

**Comment by saiprashanths** [comment]
Done!
