### ISSUE TITLE
Missing Theano, Lasagne in the image

### ISSUE THREAD

**Issue by proact** [saiprashanths/dl-docker#7]
Launched Jupyter, can't see Theano, Lasagne, Keras. What did I do wrong?

![2016-06-23 14 17 19](https://cloud.githubusercontent.com/assets/3780114/16301355/08c2a31a-3956-11e6-9e09-c60531e5588f.png)

CPU version, installed via docker pull.

Among unusual stuff during installation was only that several packages already existed:

"mac ~ $ docker pull floydhub/dl-docker:cpu
cpu: Pulling from floydhub/dl-docker
6c953ac5d795: Already exists 
3eed5ff20a90: Already exists 
f8419ea7c1b5: Already exists 
51900bc9e720: Already exists 
a3ed95caeb02: Already exists 
46bb9e850895: Pull complete 
e07079b02cd9: Pull complete 
45bd5a47614d: Pull complete 
4ba5917b4dc5: Pull complete 
e197926eeea3: Pull complete 
376f5cc0ea36: Pull complete 
590b9a27bdc2: Pull complete 
4377eaedc7bc: Pull complete 
ed3b9bf2301a: Pull complete 
aac3c3ae382f: Pull complete 
13397679ef8c: Pull complete 
62d30df21bd1: Pull complete 
3329da8ba1ff: Pull complete 
669806fb3edd: Pull complete 
43a371cb28cc: Pull complete 
ffa9a85a3cc7: Pull complete "

**Comment by saiprashanths** [comment]
You didn't do/there isn't anything wrong. The other packages are install elsewhere and not in the directory from which you are launching Jupyter. You should still be able to use the other packages in your Notebook.

Also, docker does some caching. It's possible that some of the layers were already present in your system (from a previous/different pull).
