### ISSUE TITLE
Script appears to freeze at 65% at cutorch

### ISSUE THREAD

**Issue by ProGamerGov** [saiprashanths/dl-docker#9]
```
Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /root/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5")
-- MAGMA not found. Compiling without MAGMA support
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s):
-- got cuda version 7.5
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-2897/cutorch/build
[  2%] [ 10%] [ 10%] [ 10%] [ 13%] [ 15%] [ 18%] [ 21%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
[ 23%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath2.cu.o
[ 26%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathBlas.cu.o
[ 28%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathCompare.cu.o
[ 31%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathCompareT.cu.o
[ 34%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathMagma.cu.o
[ 36%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPairwise.cu.o
[ 39%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPointwise.cu.o
[ 42%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathScan.cu.o
[ 44%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathTransformReduce.cu.o
[ 47%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMasked.cu.o
[ 50%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorIndex.cu.o
[ 52%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorConv.cu.o
[ 55%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorRandom.cu.o
[ 57%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorScatterGather.cu.o
[ 60%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorSort.cu.o
[ 63%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o
[ 65%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTypeUtils.cu.o
```

**Comment by saiprashanths** [comment]
`cutorch` does take a while to compile. Did it finish eventually?

**Comment by iassael** [comment]
Same here in working Docker with both in Ubuntu 14.04 and Ubuntu 16.04 with CUDA 8.0 and CuDNN 5.1.

**Comment by riccitensor** [comment]
For me the same, first 

`
-- Found Torch7 in /Users/fenek/torch/install
-- MAGMA not found. Compiling without MAGMA support
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;5.2+PTX
-- got cuda version 7.5
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/fenek/torch/extra/cutorch/build
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[ 22%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o
[ 25%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o
[ 27%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathCompare.cu.o
[ 30%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathCompareT.cu.o
[ 32%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o
[ 35%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o
[ 37%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPointwise.cu.o
[ 40%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathReduce.cu.o
[ 42%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathScan.cu.o
[ 45%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMasked.cu.o
[ 47%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorIndex.cu.o
[ 50%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorConv.cu.o
[ 52%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorRandom.cu.o
[ 55%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorScatterGather.cu.o
[ 57%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorSort.cu.o
[ 60%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o
[ 62%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTypeUtils.cu.o`
